### ISSUE TITLE
영화목록에서 데이터 종류

### ISSUE THREAD

**Issue by whtjdqja9923** [whtjdqja9923/OpenSourcePrj#17]
포스터, 제목, 제작연도, 종류, 상영시간, 평점(수집한거), 평가
이정도면 될것같은데 어떠세요?

**Comment by overline3021** [comment]
종류는 장르를 말씀하신 거죠?
그 정도 정보면 충분할 것 같습니다.

**Comment by whtjdqja9923** [comment]
넵! 뭘 더 넣으면 지저분해질것 같아서요...
