### ISSUE TITLE
영화인 화면 구성 관련

### ISSUE THREAD

**Issue by whtjdqja9923** [whtjdqja9923/OpenSourcePrj#18]
자료수집이 어려워서 배우 사진은 힘들것같고
표 형태로 하려고 하는데 확인좀 부탁드려요

**Comment by overline3021** [comment]
표 형태라고 하심은 웹페이지에서 출력 형태를 말씀하신 건가요?
배우 사진은 필수까지는 아니라고 생각해서 없어도 괜찮을 것 같네요.

**Comment by whtjdqja9923** [comment]
넵 사진은 수집하긴 여건상 힘들어서 표로 하려구요
