### ISSUE TITLE
프로젝트 주제선정

### ISSUE THREAD

**Issue by whtjdqja9923** [whtjdqja9923/OpenSourcePrj#2]
프로젝트 주제선정 관련하여 교수님께서 말씀하신 차별점에 대한 의견, 추가로 제안하실 주제가 있으시면 적어주시면 됩니다.

* 프로젝트 주제 : 무엇이든 "예측"과 관련된 사항

**<프로젝트 주제 후보>**
1. 영화추천
2. 주가 예측
3. 카드사용량 예측

**Comment by whtjdqja9923** [comment]
차별점 내용 : 기존 시청한영화 평점기반 + 챗gpt api 활용한 줄거리기반 추천
실현가능성 : 낮음
예상이슈 : 영화 관련 데이터셋 구축, 관련기술 활용능력 미숙, api 비용발생 가능성 등

**Comment by overline3021** [comment]
저는 개인적으로 프로젝트 관련 경험이 없어서 다른 분들 중에도 경험이 있으신 분이 안 계시다면 중복이더라도 참고자료가 많을 것 같은 영화추천 프로그램으로 진행하고 여력이 남으면 차별성 부분으로 추가해 나가는 방식이 어떨까 싶습니다.

일단 제가 생각해놓은 차별점은

1. 배우 추천: 이전 시청기록에서 자주 겹치는 배우의 영화라던가 같은 배우를 선호하는 사람들이 많이 본 영화를 추천하는 방식의 기능 (감독의 경우도 가능)

2. 책정 점수기반 추천: 영화 시청 후 마음에 들지 않는 영화였어도 시청기록이 남아 추천 알고리즘에 관련영화가 뜰 수 있기 때문에 시청후 영화별 점수를 책정하는 기능을 추가해 본인이 책정한 점수를 토대로 영화를 추천해주는 기능

3. 취향별 평점 기능: 취향별로 장르마다의 평점기준이 다르기 때문에 비슷한 취향의 사람들 기준의 평점을 따로 집계해 표시해주는 기능

일단 이렇게 3가지 생각해봤습니다. 최대한 연계 가능할 것 같은 기능을 생각해봤는데 아무래도 관련 경험이 없다보니 현실성이 떨어지는 제안일 수도 있음을 고려하고 봐주시길 바랍니다.

**Comment by Shin0909-dev** [comment]
저는 영화 추천도 좋지만 새로 개봉할 영화가 계절, 장르, 감독, 제작사, 이름, 출연진, 스태프 수, 투입한 돈 등을 이용하여 어느정도의 관객수를 가질 수 있을지 예측하는 것도 좋을 것 같습니다. 아니면 과거에 계절별로 잘나갔던 장르나 영화들의 상세정보를  조합해 현재 개봉 예정인 영화의 계절, 장르, 감독, 제작사, 이름, 출연진, 스태프 수, 투입한 돈 등을 현재 계절에 맞는 영화를 추천해주는 것도 나쁘지 않을 것 같습니다.

**Comment by whtjdqja9923** [comment]
말씀주신 내용을 바탕으로 정리하였습니다 최종결정은 내일 교수님 피드백받고 확정할 예정입니다
1. 주제 : 영화추천 프로그램
2. 사용자 : 일반소비자
3. 기본기능 : 영화별 평가점수, 선호배우 바탕 새로운 영화 추천
4. 차별기능 : (1) 전체사용자가 아닌 연령, 성별, 선호 장르에 기반한 유사집단 평점점수 / (2) 감독, 출연진, 시놉시스 등 기반한 관객수예상 / (3) 챗gpt 등을 활용한 대화형 추천
5. 예상이슈 : 이미지 등 영화관련 데이터셋 구축

**Comment by whtjdqja9923** [comment]
<결정사항> 교수님 피드백 후 이대로 확정합니다!(변경사항 X)

1. 주제 : 일반유저들을 대상으로 한 영화추천 프로그램
2. 기본기능 : 영화별 평가점수, 선호배우 바탕 새로운 영화 추천
3. 차별기능 : 기본기능 완성 후 순서대로 서비스 확대
   (1) 전체사용자가 아닌 연령, 성별, 선호 장르에 기반한 유사집단 평점점수
   (2) 감독, 출연진, 시놉시스 등 기반한 관객수예상
   (3) 챗gpt 등을 활용한 대화형 추천
4. 프로젝트 위험 : 이미지, 영화목록, 평점 등 영화관련 데이터셋 구축

* 데이터셋의 경우 교수님께서도 말씀하신 만큼 프로젝트 위험으로 인지하고 지속적으로 관리해야 하겠습니다.
