### ISSUE TITLE
추천기능 진행상황 관련

### ISSUE THREAD

**Issue by whtjdqja9923** [whtjdqja9923/OpenSourcePrj#21]
데이터 수집, 기본기능(영화목록, 영화인목록, 평가)는 거의 다 되어갑니다
추천은 어떻게 되어가는지요?

**Comment by overline3021** [comment]
추천 기능은 우선은 완성 단계이고 html로 웹페이지에 출력하는 단계만 완료하면 됩니다.

**Comment by whtjdqja9923** [comment]
다행이네요 고생하셨습니다
제 부분은 완료한 것 같습니다
