### ISSUE TITLE
메인화면 관련

### ISSUE THREAD

**Issue by whtjdqja9923** [whtjdqja9923/OpenSourcePrj#23]
아이콘 위주로 심플하게 구성하려고 하는데 생각해 둔 것 있으실까요?

**Comment by overline3021** [comment]
각 페이지로 이동할 수 있는 아이콘만 깔끔하게 구성하는 편이 저도 좋아보입니다.

**Comment by whtjdqja9923** [comment]
넵~! 영화추천 페이지만 추가하면 끝나겠네요
