### ISSUE TITLE
DB 컬럼 데이터타입 변경

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#29]
혹시 rating 컬럼에서 score, rating count, source, max score를 FLOAT 형으로 수정 해주실 수 있을까요?

**Comment by whtjdqja9923** [comment]
계산할때 쓰실거면 형변환 해서 쓰시면 될것같습니다~!
score는 사이트 평가점수(평균)이고 rating count는 평가에 참여한 사람 수에요
개인별 weighted rating를 별도로 저장해야하나요?
그러면 type을 지정하고 member code랑 movie code를 넣으면 될 것 같긴 합니다

**Comment by overline3021** [comment]
rating 테이블에 weighted score 컬럼을 추가해서 사용하도록 하겠습니다.
