### ISSUE TITLE
프로그램 구현 방식

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#3]
@Shin0909-dev @whtjdqja9923 
프로그램을 어떤 형식으로 구현할 지에 대한 논의가 필요하다고 생각합니다. (ex. 웹, 안드로이드 앱 등)

**Comment by whtjdqja9923** [comment]
영화추천이라는 서비스 특성 상 pc나 노트북으로도 많이 접근하기 때문에 웹으로 구현하는게 나을 듯 싶습니다.
아무래도 웹서비스에 운영까지 감안하면 스프링부트 쓰는게 좋아보입니다만 프로젝트 특성 상 특정기술을 반드시 써야한다! 이런것은 없기 때문에 가볍게 파이썬(플라스크) 써도 상관없을듯 싶습니다.
레퍼런스 많은 언어가 유리하지 않을까 싶습니다.
프론트의 경우 복잡하게 react나 vue 쓰기보단 타임리프 정도로 간단하게 가는게 좋아보입니다

**Comment by Shin0909-dev** [comment]
아무래도 2학년 수업으로 모두 처음이다 보니까 가능한 쉬운 언어로 간단하게 구현하는게 좋아보입니다. 저는 파이썬이 좋을 것 같습니다.

**Comment by whtjdqja9923** [comment]
언어 : 파이썬 3.11
웹서버 : nginx/apache(추후적용) + Flask
DB(필요시) : MySQL

주말에 프로젝트 생성해서 MR하겠습니다~~
