### ISSUE TITLE
코사인 유사도 관련

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#34]
movie_detail 테이블의 synopsis 컬럼을 확인하지 못했어서 이전에 말씀드린 대로 단순하게 하려고 했던 거였는데 다시 synopsis 기반으로 코사인 유사도를 계산하는 방식으로 진행하곘습니다.

**Comment by whtjdqja9923** [comment]
넵! 알겠습니다
