### ISSUE TITLE
테이블 생성, 크롤링, 유사도 계산 등

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#35]
테이블 생성, 크롤링, 유사도 계산 등 업데이트 관련 기능들을 한 파일로 묶는 건 어떨까 싶은데 어떻게 생각하시나요?

**Comment by whtjdqja9923** [comment]
별개 기능들이라 분리해놓는게 좋지 않을까 싶습니다!
