### ISSUE TITLE
[위험관리] 영화관련 데이터 셋 구축 진행사항

### ISSUE THREAD

**Issue by whtjdqja9923** [whtjdqja9923/OpenSourcePrj#4]
영화관련 데이터셋의 진행사항을 공유하기 위한 이슈입니다.

다음과 같은 순서로 진행할 것 같으니 진행사항 있으면 여기에 댓글달아주세요

1. 크롤링, 다운로드 등이 가능한 유사DB 조사
2. 테이블 논리/물리 설계
3. DDL작성 및 DB내 테이블 생성
4. 테이터 적재

* 이 이슈는 닫지 마세요
* 2주 단위로 진행상황을 확인할 예정입니다.

**Comment by overline3021** [comment]
2번은 imdb와 로튼토마토와 영진위의 평점을 평균 내자는 건가요?
찾아보니까 서로 영화ID가 다르면 매핑을 해야 한다고 하던데 두 API에서는 같은 영화ID를 공유하나요?

**Comment by whtjdqja9923** [comment]
진행상황 공유

- 영진위 데이터 수집 진행중(영화목록 : 완료, 배우목록 : 진행중, 영화상세/배우상세 : 추후)*
* 하루 API 콜 수가 제한되어있어 시일이 좀 걸릴것 같습니다(1~2주 예상)

- 로튼토마토, imdb : 수집방법 설계 중(금주 내 마무리 예정)
