### ISSUE TITLE
기말 발표자료(수정)

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#42]
발표 멘트는 연습해보면서 수정할 예정이고 제 파트 내용만 추가로 작성하였습니다.
https://docs.google.com/presentation/d/1qmQAQq5pVwJauN-8WBN_7ohBiU-jjZA8/edit?usp=drive_link&ouid=103268350319505660087&rtpof=true&sd=true

**Comment by whtjdqja9923** [comment]
공유제한이 걸려있어서 다운이 안되네요...
메일로 보내주시면 감사하겠습니다

**Comment by overline3021** [comment]
예 알겠습니다.
