### ISSUE TITLE
기말 발표 주의사항

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#43]
발표시간 8~10분 맞추는 것 외에 추가로 주의해야 할 점 있을까요?

**Comment by whtjdqja9923** [comment]
아뇨 지난번처럼 시간 보여드릴테니 발표하시면 될 것 같습니다.
다만 좀 빨리하시는 경향이 있어서 천천히 하시는게 좋을것 같아요
