### ISSUE TITLE
데이터셋 파일형식

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#6]
추후에 크롤링할 영화평점 등의 파일들은 .json 으로 가져올 예정인가요?
그것에 맞춰서 작성해두려고 합니다.

**Comment by whtjdqja9923** [comment]
몽고DB 써서 저장해놓을테니 그거 쿼리날리셔서 쓰시면 됩니다
ERD는 별도 이슈 확인하셔요!
