### ISSUE TITLE
Feature_영화추천: 피드백

### ISSUE THREAD

**Issue by overline3021** [whtjdqja9923/OpenSourcePrj#7]
Feature_영화추천 브랜치의 movie-recommendation/movie_util.py처럼 작성해서 recommendation.py에서 import하여 사용할 계획인데 혹시 문제점이 있거나 생긴다면 지적해주시면 감사하겠습니다.

**Comment by whtjdqja9923** [comment]
모듈 분리해서 작성하시려고 하는 것 같은데 좋은 방향인것 같습니다!
