### ISSUE TITLE
ERD 관련 진행상황 공유 및 확인요청

### ISSUE THREAD

**Issue by whtjdqja9923** [whtjdqja9923/OpenSourcePrj#9]
오늘 실습한 모델러 활용해서 ERD 작성했습니다.
* 영진위 데이터만 작성한 상태이고 추가될 예정입니다
* 영화/영화상세/배우/배우상세
* (참고) https://www.kobis.or.kr/kobisopenapi/homepg/apiservice/searchServiceInfo.do

확인해보시고 피드백 부탁드리겠습니다!
* 필요한 데이터 등...

[movie_recommendation_erd_v1.pdf](https://github.com/whtjdqja9923/OpenSourcePrj/files/11437764/movie_recommendation_erd_v1.pdf)

**Comment by overline3021** [comment]
영화 평점 항목 추가가 필요할 것 같습니다.

**Comment by whtjdqja9923** [comment]
평점남긴 이용자 수의경우
원하는 영화의 movie code와 source가 user인 경우를 select count로 쿼리문 날려주시면 됩니다~

ex. flask sqlite 모듈 썼을때 입니다~
query = '''
SELECT count(*) FROM rating r WHERE "movie code" = ? and source = "user"
'''
cursor.execute(query, movie_code)

**Comment by whtjdqja9923** [comment]
현재 ERD 올려드려요
[영화추천.zip](https://github.com/whtjdqja9923/OpenSourcePrj/files/11607321/default.zip)
